# -*- coding: utf-8 -*-
"""Phase 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbz91UaJ9x6ejdYCMrzRkJypeDBLTT5l
"""

a=int(input("Enter the value of A"))
b=int(input("Enter the value of B"))
print("Before exchanging the values")
("A=",a,"B=",b)
temp=a
a=b
b=temp
print("After exchanging the valuesof the variables")
("A=",a,"B=",b)